spring:
  application:
    name: "Journal App"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:

  data:
    mongodb:
          uri: ${MONGODB_URI}
          database: journaldb
          auto-index-creation: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000


server:
  servlet:
    context-path: /journal
  port: 8080

#  ${MONGODB_URI}
#  ${MAIL_USERNAME}
#  ${MAIL_PASSWORD}
#  ${REDIS_URL}