apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-app
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: springboot-app
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
